config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # 1. List all pets
  get '/pets', to: 'pets#index', as: :pets
  post '/pets', to: 'pets#create'
  get '/pets/new', to: 'pets#new', as: :new_pet #=> DISPLAY THE FORM
  get '/pets/:id', to: 'pets#show', as: :pet
  delete '/pets/:id', to: 'pets#destroy'
  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch '/pets/:id', to: 'pets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['dog', 'cat', 'bird', 'hamster']

  validates :name, :address, :found_on, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    # raise
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    if @pet.destroy
      redirect_to pets_path, status: :see_other
    else
      render :show, status: :unprocessable_entity
    end
  end
  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPetsLivecode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :found_on %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <% if pet.new_record? %>
    <%= f.submit 'Report pet', class: 'btn btn-primary' %>
  <% else %>
    <%= f.submit 'Update pet', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<div class="container">
<h1>Lost Pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <%= link_to pet.name, pet_path(pet) %> found <%= pluralize(pet.found_days_ago, 'day')%> ago
    </li>
  <% end %>
</ul>

<%= link_to 'Report pet', new_pet_path, class: 'btn btn-primary'%>

</div>

app/views/pets/new.html.erb
<h1>Report found pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1>This is <%= @pet.name %></h1>

<img src="https://source.unsplash.com/random?<%= @pet.species %>" alt="<%= @pet.species%> image" width="200">

<p>Address: <%= @pet.address %> </p>
<p>Species: <%= @pet.species %></p>
<p>Found: <%= @pet.found_on %></p>

<%= link_to 'See all pets', pets_path %>

<%= link_to 'Edit this pet', edit_pet_path(@pet) %>

<%= link_to 'Adopt pet (delete)', pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>